name: Publish Docker
on: 
  push: 
    branches: 
      - master
jobs:
  latest-and-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: DockerHub login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: set up docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: get tag name
        id: tagName
        uses: olegtarasov/get-tag@v2
      - name: build dockerfile and push to dockerhub
        run: |
          REPO_NAME="xavierniu/cloudreve"
          if [[ -z "$GIT_TAG_NAME" ]]; then \
            echo "no git tag here"; \
            docker buildx build \
            --platform=linux/amd64,linux/arm/v7,linux/arm64 \
            -t ${REPO_NAME}:latest -t $REPO_NAME:amd64 \
            --push \
            . -f Dockerfile; \
          else \
            echo "tag existed! TAG: ${GIT_TAG_NAME}"; \
            docker buildx build \
            --platform=linux/amd64,linux/arm/v7,linux/arm64 \
            -t ${REPO_NAME}:latest -t ${REPO_NAME}:amd64 -t ${REPO_NAME}:${GIT_TAG_NAME}-amd64 \
            --push \
            . -f Dockerfile; \
          fi
