name: Publish Docker
on: 
  push: 
    branches: 
      - master
jobs:
  latest-and-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: DockerHub login
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      - name: set up docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: get tag name
        id: tagName
        uses: olegtarasov/get-tag@v2
      - name: build dockerfile and push to dockerhub
        run: |
          REPO_NAME="xavierniu/cloudreve"
          TAGS="$REPO_NAME:latest $REPO_NAME:amd64"
          echo "GIT TAG: ${GIT_TAG_NAME}, REPO NAME: ${REPO_NAME}, TAGS: ${TAGS}"
          if [[ -z "$GIT_TAG_NAME" ]]; then \
            echo "no git tag here" \
          else \
            TAGS+=" $REPO_NAME:${GIT_TAG_NAME}-amd64" \
            echo "tag existed! TAG: ${TAGS}" \
          fi
          docker buildx build \
          --platform=linux/amd64,linux/arm/v7,linux/arm64 \
          --push \
          -f Dockerfile . \
          -t ${TAGS}
